load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "hello_slam",
    srcs = ["helloSLAM.cpp"],
)

cc_library(
    name  = "hello",
    srcs = ["libHelloSLAM.cpp"],
    hdrs = ["libHelloSLAM.h"],
)